name: AirsideAutoDelete
services:
    autodelete:
        ports:
            - 2202:2202/tcp
        container_name: Autodelete
        volumes:
            - /opt/AutoDelete/config.yml:/autodelete/config.yml
            - /opt/AutoDelete/data/:/autodelete/data/
        restart: always
        image: ghcr.io/dualmoon/AirsideAutoDelete:latest

