name: airside_auto_delete
services:
    autodelete:
        ports:
            - 2202:2202/tcp
        container_name: Autodelete
        volumes:
            - ./AutoDelete/config.yml:/autodelete/config.yml
            - ./AutoDelete/data/:/autodelete/data/
        restart: always
        image: ghcr.io/dualmoon/airsideautodelete:master

